[tool.poetry]
name = "paybackbenefitsmaximizer"
version = "0.1.0"
description = ""
authors = ["xi&jiatong"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
